build: off

version: 0.0.1.{build}

image:
  - Visual Studio 2017

branches:
  only:
    - master

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
        
    clone_folder: C:/stack
