build: off

version: 0.0.1.{build}

image:
  - Visual Studio 2017
  - Ubuntu
configuration:
  - Release
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    environment:
      OS: windows
    test_script:
      - ps: write-host $Env:OS

  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      OS: linux
    test_script:
      - sh: echo $OS
