build: off

version: 0.0.1.{build}

image:
  - Visual Studio 2015
  - Ubuntu

branches:
  only:
    - master

for:
   -
    matrix:
      only:
        - image: Ubuntu
        
    environment:
      OS: linux
    
    cache:
      - '$HOME/.stack'
    
    install:
      - sh: mkdir -p ~/.local/bin
      - sh: export PATH=$HOME/.local/bin:$PATH
      - sh: curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    
    test_script:
      - sh: echo $OS
      - sh: stack --no-terminal --install-ghc test --only-dependencies
    
    after_test:
      - sh: stack install
      - sh: tar -czvf "howl-$OS-x86_64.tar.gz" "$HOME/.local/bin/howl"
      
    artifacts:
      - path: howl-*.tar.gz
        name: HowlLinux
    
    deploy:
      - provider: GitHub
        release: howl-v$APPVEYOR_BUILD_VERSION
        artifact: HowlLinux
        draft: true
        auth_token:
          secure: TVsVRmN1rXlYJyeqnh84MvFLvnqvrPsB4SKkHYy5SOrOI19rHnJfr8pcWw40zyrp
        prerelease: false
        on:
          branch: master
