version: 1.0.{build}

branches:
  only:
    - master

clone_folder: C:\stack

environment:
  global:
    STACK_ROOT: C:\sr
    TMP: C:\tmp

cache:
  - '%STACK_ROOT%'
  - 'C:\Users\appveyor\AppData\Local\Programs\stack'

install:
  - cmd: echo Installing HaskellStack..
  - cmd: set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - cmd: curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - cmd: 7z x stack.zip stack.exe
  - cmd: dir /w /p
  - cmd: echo Ending install

build: off

test_script:
  - echo start test_script
  - dir /w /p
  - stack setup > nul
  - echo "" | stack --no-terminal test

after_test:
  - stack install
  - 7z a howl.zip C:\Users\appveyor\AppData\Roaming\local\bin\howl.exe
  - dir /w /p

artifacts:
  - path: howl.zip
    name: Howl

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: howl-v$(appveyor_build_version)
    artifact: howl.zip
    draft: true
    auth_token:
      secure: TVsVRmN1rXlYJyeqnh84MvFLvnqvrPsB4SKkHYy5SOrOI19rHnJfr8pcWw40zyrp
    prerelease: false
    on:
      branch: master                # release from master branch only
